name: ESLint Test Build Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  eslint:
    name: ESLint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install pnpm
        run: |
          curl -f https://get.pnpm.io/v6.16.js | node - add --global pnpm
          echo "$(npm bin -g)" >> $GITHUB_PATH

      - name: Install dependencies
        run: pnpm install

      - name: Run ESLint
        run: pnpm run lint
